AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >
  Exam score prediction API using AWS Lambda,
  Amazon S3 and AWS SAM

Resources:

  ModelBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256


  PredictionFunction:
    Type: AWS::Serverless::Function

    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Runtime: python3.12

      Timeout: 30
      MemorySize: 512

      Environment:
        Variables:
          MODEL_BUCKET: !Ref ModelBucket
          MODEL_KEY: models/exam_score_model.joblib

      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "${ModelBucket.Arn}/models/exam_score_model.joblib"

      Events:
        PredictApi:
          Type: Api
          Properties:
            Path: /predict
            Method: post


Outputs:

  PredictionApi:
    Description: API Gateway endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict"

  ModelBucketName:
    Description: S3 bucket containing the model
    Value: !Ref ModelBucket
